### ISSUE TITLE
check-missing-requirements hook fails for python 3.12.4

### ISSUE THREAD

**Issue by RobFirth** [stfc/pre-commit-hooks#39]
Running pre-commit hooks gives the following error in python 3.12.4:

```bash
Check for missing requirements from the environment.......................Failed
- hook id: check-missing-requirements
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/berto/PycharmProjects/HT06272_RAG_Benchmarking/rag_bench/.venv/lib/python3.12/site-packages/hooks/check_missing_requirements.py", line 9, in <module>
    import requirements
  File "/Users/berto/PycharmProjects/HT06272_RAG_Benchmarking/rag_bench/.venv/lib/python3.12/site-packages/requirements/__init__.py", line 1, in <module>
    from .parser import parse   # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/berto/PycharmProjects/HT06272_RAG_Benchmarking/rag_bench/.venv/lib/python3.12/site-packages/requirements/parser.py", line 4, in <module>
    from .requirement import Requirement
  File "/Users/berto/PycharmProjects/HT06272_RAG_Benchmarking/rag_bench/.venv/lib/python3.12/site-packages/requirements/requirement.py", line 3, in <module>
    from pkg_resources import Requirement as Req
ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by RobFirth** [comment]
ensuring `setuptools` is specified as a dependency in the project python environment solves this issue. 

Interestingly, the same error can be resolved for `nbdev` using the `additional_dependencies` option:

```yml
    - repo: https://github.com/fastai/nbdev
      rev: 2.3.25
      hooks:
      - id: nbdev_clean
        additional_dependencies: [setuptools]
```

**Comment by tjeng** [comment]
> ensuring `setuptools` is specified as a dependency in the project python environment solves this issue.
> 
> Interestingly, the same error can be resolved for `nbdev` using the `additional_dependencies` option:
> 
>     - repo: https://github.com/fastai/nbdev
>       rev: 2.3.25
>       hooks:
>       - id: nbdev_clean
>         additional_dependencies: [setuptools]

The repo has moved, with the following configuration
```
    - repo: https://github.com/answerdotai/nbdev
      rev: be3fd2266e4dcd605b60d7217a838810809e857f
      hooks:
      - id: nbdev_clean
```
However, adding additional dependencies argument do not seem to install it. Still having the same error below
```
Check for missing requirements from the environment.......................Failed
- hook id: check-missing-requirements
- exit code: 1

/opt/anaconda3/bin/python: Error while finding module specification for 'hooks.check_missing_requirements' (ModuleNotFoundError: No module named 'hooks')

Check for mypy import errors..............................................Failed
- hook id: check-mypy-import-errors
- exit code: 1

/opt/anaconda3/bin/python: Error while finding module specification for 'hooks.check_mypy_import_errors' (ModuleNotFoundError: No module named 'hooks')

Check for pylint import errors............................................Failed
- hook id: check-pylint-import-errors
- exit code: 1

/opt/anaconda3/bin/python: Error while finding module specification for 'hooks.check_pylint_import_errors' (ModuleNotFoundError: No module named 'hooks')
```
